personal_portfolio/blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/portfolio/urls.py
from django.urls import path, include

from portfolio import views


urlpatterns = [
    path('', views.home, name='home'),
]

personal_portfolio/blog/models.py
from pyexpat import model
from django.db import models


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self) -> str:
        return self.title

personal_portfolio/portfolio/models.py
from distutils.command.upload import upload
from pyexpat import model
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self) -> str:
        return self.title

personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from blog.models import Blog


# Create your views here.
def blog(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

personal_portfolio/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse

from portfolio.models import Project


# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

personal_portfolio/blog/templates/blog/blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>Blogs</h1>

<h2>Jorge has written {{ blogs.count }} blog{{ blogs.count|pluralize}}</h2>

{% for blog in blogs %}

<a href="{% url 'blog:detail' blog.id %}">
    <h2>{{ blog.title }}</h2>
</a>
<p>{{ blog.date|date:'M d Y'|upper }}</p>
<p>{{ blog.description|truncatechars:5 }}</p>

{% endfor %}

{% endblock %}

personal_portfolio/blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1>{{ blog.title }}</h1>
<h2>--{{ blog.date|date:'F jS Y' }}--</h2>
{{ blog.description|safe }}

{% endblock %}

personal_portfolio/portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap demo</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>

    <body>

        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
        </script>
    </body>

</html>

personal_portfolio/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}

<a href="{% url 'blog:blog' %}">Blog</a>

<h1>This is my Portfolio</h1>

{% load static %}

<a href="{% static 'portfolio/IELTS.pdf' %}">IELTS book</a>

<img src="{% static 'portfolio/pic2.png' %}" alt="My image">

{% for project in projects %}

<h1>{{ project.title }}</h1>
<p>{{ project.description }}</p>
<img src="{{ project.image.url }}" alt=""></>

{% if project.url %}
<a href="{{ project.url }}">Link</a>
{% endif %}

{% endfor %}

{% endblock %}